name: No-Op Workflow

on: [push, pull_request]

jobs:
  no_operation_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: No operation step
      run: echo "Doing nada."
