name: Propagate Build Tags

# This GitHub Actions workflow facilitates the creation and
# deployment of a release tag based dependencies.
#
# It is triggered by a repository dispatch event from a 
# dependency, and will then (if possible) create the
# same tag in this repository
#
# Implementation note: this workflow would be a lot cleaner if
# it were to use matricies, but unfortunately at this time
# they allow allow for a single output. We need to ensure that
# ALL of the dependencies are deployed. There are some workarounds,
# but I decided that it wasn't worth the bother. So for now, all
# dependencies need to be listed one-by-one.
#  --> See: https://github.com/orgs/community/discussions/17245

on:
  repository_dispatch:
    types: [dependency-tag]

jobs:
  propagate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Check Existing oidc-rest Deployment
      id: dep1-exists
      uses: kentyou/build-automation/actions/maven-deploy-check@b5aa5036b34fd0c907df6649c9afc34635e851ef # v1.0.0
      with:
        module-path: parent
        tag-name: ${{ github.event.client_payload.tag-name }}
        artifact: 'com.kentyou.oidc:authenticator:${kentyou.oidc.version}'
        cancel-workflow: false
        repo-secret: ${{ secrets.KENTYOU_CI_PAT }}
    - name: Check Existing sensinact-gateway Deployment
      id: dep2-exists
      uses: kentyou/build-automation/actions/maven-deploy-check@b5aa5036b34fd0c907df6649c9afc34635e851ef # v1.0.0
      with:
        module-path: parent
        tag-name: ${{ github.event.client_payload.tag-name }}
        artifact: 'org.eclipse.sensinact.gateway.core:api:${sensinact.version}'
        cancel-workflow: false
        repo-secret: ${{ secrets.KENTYOU_CI_PAT }}
    - name: Check Existing kentyou-datastore Deployment
      id: dep3-exists
      uses: kentyou/build-automation/actions/maven-deploy-check@b5aa5036b34fd0c907df6649c9afc34635e851ef # v1.0.0
      with:
        module-path: parent
        tag-name: ${{ github.event.client_payload.tag-name }}
        artifact: 'com.kentyou.web.filters:rest:${kentyou.web.filters.version}'
        cancel-workflow: false
        repo-secret: ${{ secrets.KENTYOU_CI_PAT }}
    - name: Create the Tag
      if: ${{ steps.dep1-exists.outputs.exists == 'true' && steps.dep2-exists.outputs.exists == 'true' && steps.dep3-exists.outputs.exists == 'true' }}
      run: gh workflow run kentyou-create-tag.yml -f git-ref=main -f tag-name=${{ github.event.client_payload.tag-name }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
