name: Trigger the propagation of a Kentyou release tag

# This GitHub Actions workflow triggers the creation and
# deployment of a release tag based on user-specified inputs.
#
# The process is manually triggered, and allows users to specify
# both the Git reference (e.g., a commit SHA or branch name) and
# the name of the tag to be created.
#
# Once triggered, this workflow notifies all of the "root" repositories
# that constitute Kentyou's deliverables. If these root repositories
# build successfully, they will in turn notify projects that depend
# on them, and so on and so forth.

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The name of the tag to create'
        required: true
        type: string
      release-repo:
        description: 'The name of the destination repository'
        required: false
        type: string

jobs:

  notify-dependents:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo-name: ['web-filters', 'sensinact-gateway', 'kentyou-datastore', 'kentyou-eye-ui', 'simple-prediction-service']

    steps:
    - name: Notify dependents
      uses: kentyou/build-automation/actions/downstream-dispatch@c97a00fe04569dc601a316aabb0fe9068a26724b # v1.0.0
      with:
        repo-name: ${{ matrix.repo-name }}
        tag-name: ${{ inputs.tag-name }}
        repo-secret: ${{ secrets.KENTYOU_DISPATCH_PAT }}
        release-repo: ${{ inputs.release-repo  }}
